### ISSUE TITLE
FileSubpath for token search

### ISSUE THREAD

**Issue by bicukow** [thornydre/blender_path_maker#2]
Hello, can you please add FileSubPath to search for placeholder token?
The main problen is that base path in output node is creating folder, but not a file with token name/.
![image](https://github.com/user-attachments/assets/297159d0-6084-4728-af34-8d7ff84dc7ad)

something like this:

```
replace_token = '<camname>'
replace_by = bpy.context.scene.camera.name

for node in bpy.context.scene.node_tree.nodes:
    if node.type == 'OUTPUT_FILE':
        for slot in node.file_slots:
            if replace_token in slot.path:
                slot.path = slot.path.replace(replace_token, replace_by)
```

**Comment by thornydre** [comment]
Hello,
Just updated the addon on extensions.blender.org with support for File Subpath

Cheers !
